app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

index:
    path: /api/
    methods: GET
    controller: App\Controller\DefaultController::index
